<a href="https://colab.research.google.com/github/RashmiKamde/HR-Data-Analysis/blob/main/HR_Dataset.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

In [ ]:
from google.colab import files
import pandas as pd

# Upload file manually
uploaded = files.upload()

Saving HR_Dataset.xlsx to HR_Dataset (2).xlsx

In [ ]:
# Load the Excel file
file_name = 'HR_Dataset.xlsx'
xls = pd.ExcelFile(file_name)

# Display sheet names
print(xls.sheet_names)

['Employees_Details', 'Department', 'Attendance', 'Performance_Reviews']

In [ ]:
# Read each sheet into a DataFrame
employees_df = pd.read_excel(xls, sheet_name="Employees_Details")
department_df = pd.read_excel(xls, sheet_name="Department")
attendance_df = pd.read_excel(xls, sheet_name="Attendance")
performance_df = pd.read_excel(xls, sheet_name="Performance_Reviews")

In [ ]:
# Display first 5 rows of each table
employees_df.head()

,Employee_ID,First_Name,Last_Name,Age,Gender,Joining_Date,Salary,Department_ID,Email,Phone
0,121761.0,Joseph,Gilbert,39.0,Male,2022-10-04,93949.0,15.0,lucas46@gmail.com,+1-204-506-9561
1,149572.0,Timothy,Willis,47.0,Male,2022-04-22,73204.0,17.0,stevensfrank@hotmail.com,101.590.9213x09970
2,152547.0,Nathan,Dennis,45.0,Male,2017-08-24,60227.0,1.0,erobbins@ochoa-rivera.com,195.981.8819x325
3,155959.0,Shane,Huffman,44.0,Female,2021-12-18,39953.0,11.0,evansjeremy@hotmail.com,2259933901
4,191865.0,Sharon,Ramirez,21.0,Male,2019-05-02,77031.0,2.0,wshannon@combs-smith.com,001-250-341-6132x3979

In [ ]:
employees_df.shape

(100000, 10)

In [ ]:
employees_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 10 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Employee_ID    98000 non-null  float64
 1   First_Name     98000 non-null  object
 2   Last_Name      98000 non-null  object
 3   Age            98000 non-null  float64
 4   Gender         98000 non-null  object
 5   Joining_Date   98000 non-null  datetime64[ns]
 6   Salary         98000 non-null  float64
 7   Department_ID  98000 non-null  float64
 8   Email          98000 non-null  object
 9   Phone          98000 non-null  object
dtypes: datetime64[ns](1), float64(4), object(5)
memory usage: 7.6+ MB

In [ ]:
import warnings
warnings.filterwarnings('ignore')
# Define columns
num_cols = ['Employee_ID', 'Age', 'Salary', 'Department_ID']

# Fill missing values
employees_df['Employee_ID'].fillna(0, inplace=True)  # Mode is best for categorical IDs
employees_df['Age'].fillna(employees_df['Age'].median(), inplace=True)   # Median is better for Age (avoids outliers)
employees_df['Salary'].fillna(employees_df['Salary'].mean(), inplace=True)  # Mean is useful for Salary
employees_df['Department_ID'].fillna(employees_df['Department_ID'].mode()[0], inplace=True)  # Mode is best for categorical IDs

# Ensure no infinite values
employees_df.replace([np.inf, -np.inf], np.nan, inplace=True)

In [ ]:
# Convert to integer
employees_df['Employee_ID'] = employees_df['Employee_ID'].astype(int)
employees_df['Age' ] = employees_df['Age'].astype( int)
employees_df['Salary' ]= employees_df['Salary'].astype( int)
employees_df['Department_ID'] = employees_df['Department_ID'].astype( int)
#employees_df[num_cols] = employees_df[num_cols].astype(int)

In [ ]:
employees_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 10 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   Employee_ID    100000 non-null  int64
 1   First_Name     98000 non-null   object
 2   Last_Name      98000 non-null   object
 3   Age            100000 non-null  int64
 4   Gender         98000 non-null   object
 5   Joining_Date   98000 non-null   datetime64[ns]
 6   Salary         100000 non-null  int64
 7   Department_ID  100000 non-null  int64
 8   Email          98000 non-null   object
 9   Phone          98000 non-null   object
dtypes: datetime64[ns](1), int64(4), object(5)
memory usage: 7.6+ MB

In [ ]:
# fillna of ojbet type collumn
missing_names = employees_df[employees_df['First_Name'].isnull() | employees_df['Last_Name'].isnull()]
print("No. of missing values: ", len(missing_names))

No. of missing values:  3969

In [ ]:
employees_df['Email'].fillna('unknown@email.com', inplace=True)
employees_df['Phone'].fillna(0, inplace=True)

In [ ]:
# drop null records
employees_df.dropna(subset=['First_Name', 'Last_Name','Joining_Date','Gender'], inplace=True)

In [ ]:
employees_df.isna().sum()

Employee_ID      0
First_Name       0
Last_Name        0
Age              0
Gender           0
Joining_Date     0
Salary           0
Department_ID    0
Email            0
Phone            0
dtype: int64

In [ ]:
employees_df.nunique().sum()

162921

In [ ]:
employees_df.columns

Index(['Employee_ID', 'First_Name', 'Last_Name', 'Age', 'Gender',
       'Joining_Date', 'Salary', 'Department_ID', 'Email', 'Phone'],
      dtype='object')

In [ ]:
employees_df.duplicated().sum()

0

In [ ]:
employees_df['Gender'].unique()

array(['Male', 'Female', 'Other'], dtype=object)

In [ ]:
employees_df['Gender'].value_counts()

Gender
Female    42717
Male      42306
Other      3559
Name: count, dtype: int64

In [ ]:
# Remove invalid emails
import re
employees_df["Email"] = employees_df["Email"].apply(lambda x: x if re.match(r"[^@]+@[^@]+\.[^@]+", str(x)) else np.nan)
employees_df["Email"].fillna("unknown@email.com", inplace=True)

# Format phone numbers (keep only digits and ensure 10 digits)
employees_df["Phone"] = employees_df["Phone"].astype(str).apply(lambda x: re.sub(r'\D', '', x)[:10])

In [ ]:
employees_df.head()

,Employee_ID,First_Name,Last_Name,Age,Gender,Joining_Date,Salary,Department_ID,Email,Phone
0,121761,Joseph,Gilbert,39,Male,2022-10-04,93949,15,lucas46@gmail.com,1204506956
1,149572,Timothy,Willis,47,Male,2022-04-22,73204,17,stevensfrank@hotmail.com,1015909213
2,152547,Nathan,Dennis,45,Male,2017-08-24,60227,1,erobbins@ochoa-rivera.com,1959818819
3,155959,Shane,Huffman,44,Female,2021-12-18,39953,11,evansjeremy@hotmail.com,2259933901
4,191865,Sharon,Ramirez,21,Male,2019-05-02,77031,2,wshannon@combs-smith.com,0012503416

In [ ]:
employees_df.shape

(88582, 10)

In [ ]:
department_df.head(5)

   Department_ID    Department_Name      Manager_Name
0              1     Hit Department       Betty Young
1              2    Step Department       Linda Olsen
2              3    Such Department     Denise Murray
3              4    Meet Department   Travis Crawford
4              5  Memory Department  Sarah Richardson

In [ ]:
department_df.shape

(20, 3)

In [ ]:
department_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 3 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Department_ID    20 non-null     int64
 1   Department_Name  20 non-null     object
 2   Manager_Name     20 non-null     object
dtypes: int64(1), object(2)
memory usage: 612.0+ bytes

In [ ]:
department_df.isna().sum()

Department_ID      0
Department_Name    0
Manager_Name       0
dtype: int64

In [ ]:
department_df.duplicated().sum()

0

In [ ]:
department_df.nunique()

Department_ID      20
Department_Name    20
Manager_Name       20
dtype: int64

In [ ]:
attendance_df.head()

   Attendance_ID  Employee_ID       Date Check_In_Time Check_Out_Time   Status
0       522502.0     108591.0 2024-03-06      16:54:45       00:56:40  Present
1       514679.0     108575.0 2024-08-23      20:05:55       00:47:47   Absent
2       586731.0     126457.0 2024-07-31      23:43:12       17:27:19  Present
3       522839.0     156866.0 2024-04-14      02:01:57       02:39:46  Present
4       510182.0     153661.0 2024-11-09      15:43:34       16:18:16  Present

In [ ]:
attendance_df.shape

(100000, 6)

In [ ]:
attendance_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 6 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Attendance_ID   98000 non-null  float64
 1   Employee_ID     98000 non-null  float64
 2   Date            98000 non-null  datetime64[ns]
 3   Check_In_Time   98000 non-null  object
 4   Check_Out_Time  98000 non-null  object
 5   Status          98000 non-null  object
dtypes: datetime64[ns](1), float64(2), object(3)
memory usage: 4.6+ MB

In [ ]:
attendance_df.isna().sum()

Attendance_ID     2000
Employee_ID       2000
Date              2000
Check_In_Time     2000
Check_Out_Time    2000
Status            2000
dtype: int64

In [ ]:
missing_attendance_count = attendance_df["Attendance_ID"].isnull().sum()
total_records = len(attendance_df)
print(f"Missing Attendance_IDs: {missing_attendance_count} out of {total_records}")

Missing Attendance_IDs: 2000 out of 100000

In [ ]:
attendance_df["Attendance_ID"] = attendance_df.groupby("Employee_ID")["Attendance_ID"].transform(lambda x: x.fillna(method="ffill").fillna(method="bfill"))

In [ ]:
attendance_df.dropna(subset=['Attendance_ID','Date','Check_In_Time','Check_Out_Time','Status'],inplace=True )

In [ ]:
attendance_df.isna().sum()

Attendance_ID     0
Employee_ID       0
Date              0
Check_In_Time     0
Check_Out_Time    0
Status            0
dtype: int64

In [ ]:
attendance_df['Attendance_ID']=attendance_df['Attendance_ID'].astype(int)
attendance_df['Employee_ID']=attendance_df['Employee_ID'].astype(int)

In [ ]:
attendance_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 89690 entries, 0 to 99999
Data columns (total 6 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Attendance_ID   89690 non-null  int64
 1   Employee_ID     89690 non-null  int64
 2   Date            89690 non-null  datetime64[ns]
 3   Check_In_Time   89690 non-null  object
 4   Check_Out_Time  89690 non-null  object
 5   Status          89690 non-null  object
dtypes: datetime64[ns](1), int64(2), object(3)
memory usage: 4.8+ MB

In [ ]:
attendance_df.duplicated().sum()

0

In [ ]:
performance_df.head(5)

,Review_ID,Employee_ID,Review_Date,Performance_Rating,Feedback,Promotion_Eligible
0,786430.0,170832.0,2024-01-14,3.0,Short side yet check account face full.,No
1,791978.0,138040.0,2024-09-26,2.0,Administration west free have another result t...,No
2,725621.0,157261.0,2024-07-30,3.0,Would early door audience sing myself those ev...,Yes
3,761593.0,138276.0,2024-11-03,5.0,Occur hope base nothing owner against spend ha...,Yes
4,711515.0,160124.0,2024-10-27,3.0,See during seek base place of reason maybe ide...,No

In [ ]:
performance_df.isna().sum()

Review_ID             2000
Employee_ID           2000
Review_Date           2000
Performance_Rating    2000
Feedback              2000
Promotion_Eligible    2000
dtype: int64

In [ ]:
# Fill missing values in 'promotion_eligible' where 'Performance_Rating' is 5
performance_df.loc[(performance_df["Performance_Rating"] == 5) & (performance_df["Promotion_Eligible"].isnull()), "Promotion_Eligible"] = "Yes"

In [ ]:
performance_df['Feedback'] = performance_df['Feedback'].fillna('No Feedback Received')
# performance_df['Feedback'].fillna('No Feedback Received',inplace =True)

In [ ]:
performance_df.dropna(subset=['Review_ID','Employee_ID','Performance_Rating','Review_Date','Promotion_Eligible'],inplace=True)

In [ ]:
performance_df.isna().sum()

Review_ID             0
Employee_ID           0
Review_Date           0
Performance_Rating    0
Feedback              0
Promotion_Eligible    0
dtype: int64

In [ ]:
performance_df.duplicated().sum()

0

In [ ]:
performance_df['Review_ID'] = performance_df['Review_ID'].astype(int)
performance_df['Employee_ID'] = performance_df['Employee_ID'].astype(int)
performance_df['Performance_Rating'] = performance_df['Performance_Rating'].astype(int)

In [ ]:
performance_df.head()

,Review_ID,Employee_ID,Review_Date,Performance_Rating,Feedback,Promotion_Eligible
0,786430,170832,2024-01-14,3,Short side yet check account face full.,No
1,791978,138040,2024-09-26,2,Administration west free have another result t...,No
2,725621,157261,2024-07-30,3,Would early door audience sing myself those ev...,Yes
3,761593,138276,2024-11-03,5,Occur hope base nothing owner against spend ha...,Yes
4,711515,160124,2024-10-27,3,See during seek base place of reason maybe ide...,No

In [ ]:
performance_df.tail()

,Review_ID,Employee_ID,Review_Date,Performance_Rating,Feedback,Promotion_Eligible
99995,763055,123660,2023-12-03,4,Present else government interview source happy.,No
99996,786675,189089,2024-04-10,4,Break them bank chair student position five ho...,No
99997,780677,126953,2023-10-03,4,No Feedback Received,No
99998,753765,186025,2025-01-31,1,Market student scene special dark drive moment...,Yes
99999,789926,158203,2024-09-19,2,Manager if notice democratic already option vo...,Yes

In [ ]:
performance_df.shape

(92626, 6)